import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });
const hostGrotesk = Host_Grotesk({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-host-grotesk',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${hostGrotesk.variable}`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
